meta:
  title: Introduction to Kaggle for Software Engineers
  thumbnail:
  description: ソフトウェア開発者がとりあえずKaggleを始める方法
  sns:
    - twitter
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - python
    plugins:
      - line-numbers
    theme: default
  chart: false
  math: true
extends:
  js:
  css: ./style.css
  webpack:
build:
  ssr: true
